### ISSUE TITLE
Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/UnsupportedDataTypeException

### ISSUE THREAD

**Issue by OfirD1** [lynnlyc/APK_CG#1]
I'm getting the exception in the title. What should I do?
Full trace:
INFO: initializing...
Exception in thread "main" java.lang.NoClassDefFoundError: javax/activation/UnsupportedDataTypeException
	at Config.init(Config.java:122)
	at Main.generateCGForAPK(Main.java:28)
	at Main.main(Main.java:15)
Caused by: java.lang.ClassNotFoundException: javax.activation.UnsupportedDataTypeException
	at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(BuiltinClassLoader.java:582)
	at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(ClassLoaders.java:185)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:496)
	... 3 more

**Comment by yuanchun-li** [comment]
Are you using Java 9? If yes, downgrading to Java 7 or 8 might help.
Many of the javax.* APIs are deprecated in Java 9.

**Comment by JunTomyang** [comment]
@ylimit  Hi ylimit, I installed java 7but got the following error and I have tried close the firewall. Please give me some advice:)
Error:Abnormal build process termination: 
"C:\Program Files\Java\jdk1.7.0_80\bin\java.exe" -Xmx700m -Djava.awt.headless=true -Djava.endorsed.dirs=\"\" -Djdt.compiler.useSingleThread=true -Dpreload.project.path=C:/Users/qiuju/Downloads/APK_CG-master/APK_CG-master -Dpreload.config.path=C:/Users/qiuju/.IntelliJIdea2018.1/config/options -Dcompile.parallel=false -Drebuild.on.dependency.change=true -Djava.net.preferIPv4Stack=true -Dio.netty.initialSeedUniquifier=-4221528087235023747 -Dfile.encoding=windows-1252 -Duser.language=en -Duser.country=AU -Didea.paths.selector=IntelliJIdea2018.1 "-Didea.home.path=C:\Program Files\JetBrains\IntelliJ IDEA 2018.1.6" -Didea.config.path=C:\Users\qiuju\.IntelliJIdea2018.1\config -Didea.plugins.path=C:\Users\qiuju\.IntelliJIdea2018.1\config\plugins -Djps.log.dir=C:/Users/qiuju/.IntelliJIdea2018.1/system/log/build-log "-Djps.fallback.jdk.home=C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/jre64" -Djps.fallback.jdk.version=1.8.0_152-release -Dio.netty.noUnsafe=true -Djava.io.tmpdir=C:/Users/qiuju/.IntelliJIdea2018.1/system/compile-server/apk_cg-master_476b857f/_temp_ -Djps.backward.ref.index.builder=true -Dkotlin.incremental.compilation=true -Dkotlin.daemon.enabled -Dkotlin.daemon.client.alive.path=\"C:\Users\qiuju\AppData\Local\Temp\kotlin-idea-6282436105699475074-is-running\" -classpath "C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/jps-launcher.jar;C:/Program Files/Java/jdk1.7.0_80/lib/tools.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/optimizedFileManager.jar" org.jetbrains.jps.cmdline.Launcher "C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/jna.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/jna-platform.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/netty-all-4.1.13.Final.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/idea_rt.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/jdom.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/aether-1.1.0-all.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/annotations.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/oro-2.0.8.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/javac2.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/protobuf-java-3.0.0.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/platform-api.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/aether-dependency-resolver.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/trove4j.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/slf4j-api-1.7.10.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/jps-builders.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/util.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/httpcore-4.4.5.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/jps-builders-6.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/commons-codec-1.9.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/resources_en.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/commons-logging-1.2.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/guava-21.0.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/jps-model.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/httpclient-4.5.2.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/jgoodies-forms.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/snappy-in-java-0.5.1.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/maven-aether-provider-3.3.9-all.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/log4j.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/forms_rt.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/lz4-java-1.3.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/nanoxml-2.2.3.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/asm-all.jar;;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/gson-2.8.2.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/jarutils.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/guava-21.0.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/android-base-common.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/gradle/lib/gradle-api-4.4.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/gson-2.8.2.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/jarutils.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/lib/guava-21.0.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/android-base-common.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/gradle/lib/gradle-api-4.4.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/ant/lib/ant-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/uiDesigner/lib/jps/ui-designer-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/IntelliLang/lib/intellilang-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Groovy/lib/groovy-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Groovy/lib/groovy-rt-constants.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/eclipse/lib/eclipse-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/eclipse/lib/common-eclipse-util.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/maven/lib/maven-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/maven/lib/plexus-utils-2.0.6.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/osmorc/lib/osmorc-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/osmorc/lib/bndlib-3.3.0.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/osmorc/lib/bnd-repository-3.3.0.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/osmorc/lib/bnd-resolve-3.3.0.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/osmorc/lib/plexus-utils-3.0.10.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/osmorc/lib/bundlor-all.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/aspectj/lib/aspectj-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/flex/lib/flex-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/flex/lib/flex-shared.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/gradle/lib/gradle-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/devkit/lib/devkit-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/JavaEE/lib/javaee-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/JavaEE/lib/jps/jpa-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/webSphereIntegration/lib/jps/webSphere-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/weblogicIntegration/lib/jps/weblogic-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/dmServer/lib/dmServer-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/GwtStudio/lib/gwt-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/GoogleAppEngine/lib/google-app-engine-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/GoogleAppEngine/lib/appEngine-runtime.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Grails/lib/grails-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Grails/lib/grails-compiler-patch.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/jps/android-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/android-common.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/build-common.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/android-rt.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/sdk-common.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/repository.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/sdklib.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/android-base-common.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/jarutils.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/layoutlib-api.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/android/lib/manifest-merger.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Kotlin/lib/jps/kotlin-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Kotlin/lib/kotlin-stdlib.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Kotlin/lib/kotlin-reflect.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Kotlin/lib/kotlin-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Kotlin/lib/android-extensions-ide.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/Kotlin/lib/android-extensions-compiler.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/javaFX/lib/javaFX-jps-plugin.jar;C:/Program Files/JetBrains/IntelliJ IDEA 2018.1.6/plugins/javaFX/lib/common-javaFX-plugin.jar" org.jetbrains.jps.cmdline.BuildMain 127.0.0.1 49986 22c040c5-7f29-4d7e-ad90-d1ed21d2dbe3 C:/Users/qiuju/.IntelliJIdea2018.1/system/compile-server
java.lang.UnsupportedClassVersionError: org/jetbrains/jps/cmdline/Launcher : Unsupported major.minor version 52.0	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
	at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
	at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
	at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
	at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)
Exception in thread "main"
